export const CHART_ORDER = [
  "1",
  "10",
  "101",
  "1011",
  "1012",
  "1013",
  "1014",
  "1017",
  "102",
  "1021",
  "1022",
  "1023",
  "1024",
  "1028",
  "109",
  "1091",
  "1092",
  "11",
  "111",
  "1111",
  "1112",
  "1113",
  "1114",
  "1116",
  "1118",
  "112",
  "113",
  "1131",
  "1132",
  "1133",
  "1134",
  "1135",
  "1136",
  "1139",
  "114",
  "1141",
  "1142",
  "1143",
  "1144",
  "1145",
  "1146",
  "1147",
  "1148",
  "119",
  "1191",
  "1192",
  "1193",
  "1194",
  "12",
  "121",
  "1211",
  "1212",
  "1213",
  "122",
  "1221",
  "1222",
  "1223",
  "124",
  "125",
  "126",
  "129",
  "13",
  "131",
  "1311",
  "1312",
  "132",
  "1321",
  "1322",
  "1323",
  "1324",
  "133",
  "1331",
  "1332",
  "134",
  "1341",
  "1342",
  "135",
  "1351",
  "1352",
  "1358",
  "136",
  "1361",
  "1365",
  "1368",
  "137",
  "138",
  "139",
  "1391",
  "1392",
  "1393",
  "1394",
  "1395",
  "1396",
  "1397",
  "1398",
  "14",
  "141",
  "142",
  "143",
  "145",
  "146",
  "148",
  "149",
  "15",
  "151",
  "153",
  "154",
  "155",
  "159",
  "16",
  "160",
  "1601",
  "1602",
  "1608",
  "161",
  "1611",
  "1612",
  "1613",
  "1618",
  "162",
  "163",
  "164",
  "165",
  "166",
  "167",
  "168",
  "169",
  "1690",
  "1691",
  "1692",
  "1693",
  "2",
  "20",
  "201",
  "202",
  "203",
  "204",
  "205",
  "206",
  "207",
  "208",
  "209",
  "21",
  "210",
  "211",
  "212",
  "213",
  "214",
  "216",
  "217",
  "218",
  "219",
  "2190",
  "2191",
  "2192",
  "2194",
  "22",
  "221",
  "222",
  "223",
  "224",
  "225",
  "226",
  "23",
  "231",
  "232",
  "237",
  "238",
  "2381",
  "2382",
  "24",
  "241",
  "2411",
  "2412",
  "2413",
  "2414",
  "2417",
  "2418",
  "242",
  "2420",
  "2421",
  "2422",
  "2423",
  "2427",
  "2428",
  "243",
  "2430",
  "2431",
  "2432",
  "2433",
  "2434",
  "2438",
  "25",
  "251",
  "252",
  "258",
  "27",
  "271",
  "28",
  "282",
  "284",
  "2841",
  "2842",
  "2843",
  "285",
  "29",
  "290",
  "291",
  "2910",
  "2911",
  "2912",
  "2914",
  "292",
  "294",
  "2941",
  "2942",
  "2943",
  "295",
  "3",
  "30",
  "301",
  "302",
  "303",
  "304",
  "308",
  "309",
  "31",
  "311",
  "312",
  "32",
  "321",
  "329",
  "329.2023",
  "329.2024",
  "33",
  "331",
  "339",
  "4",
  "40",
  "401",
  "402",
  "403",
  "4031",
  "4032",
  "404",
  "4041",
  "4042",
  "4043",
  "405",
  "408",
  "41",
  "411",
  "412",
  "413",
  "417",
  "418",
  "42",
  "420",
  "4201",
  "4202",
  "4203",
  "4204",
  "4205",
  "4206",
  "4207",
  "4208",
  "421",
  "4211",
  "4212",
  "4213",
  "4218",
  "422",
  "4221",
  "4222",
  "4226",
  "4228",
  "43",
  "430",
  "430.1",
  "431",
  "432",
  "433",
  "434",
  "435",
  "436",
  "437",
  "438",
  "44",
  "441",
  "442",
  "443",
  "447",
  "448",
  "45",
  "451",
  "452",
  "453",
  "454",
  "455",
  "456",
  "457",
  "458",
  "46",
  "461",
  "462",
  "463",
  "464",
  "465",
  "466",
  "468",
  "47",
  "471",
  "472",
  "473",
  "474",
  "475",
  "477",
  "478",
  "48",
  "481",
  "4811",
  "4812",
  "4813",
  "4816",
  "4818",
  "482",
  "4821",
  "4822",
  "4829",
  "483",
  "49",
  "491",
  "4911",
  "4912",
  "4913",
  "4914",
  "4915",
  "492",
  "493",
  "494",
  "495",
  "496",
  "497",
  "498",
  "5",
  "50",
  "501",
  "506",
  "507",
  "51",
  "511",
  "512",
  "518",
  "58",
  "581",
  "582",
  "583",
  "6",
  "60",
  "601",
  "602",
  "603",
  "604",
  "605",
  "606",
  "607",
  "609",
  "61",
  "611",
  "612",
  "613",
  "614",
  "615",
  "616",
  "617",
  "618",
  "619",
  "62",
  "621",
  "622",
  "623",
  "624",
  "625",
  "626",
  "627",
  "628",
  "629",
  "63",
  "631",
  "632",
  "633",
  "634",
  "635",
  "636",
  "637",
  "638",
  "64",
  "641",
  "642",
  "643",
  "644",
  "647",
  "648",
  "65",
  "651",
  "652",
  "653",
  "654",
  "655",
  "656",
  "657",
  "658",
  "66",
  "661",
  "662",
  "663",
  "664",
  "665",
  "666",
  "667",
  "668",
  "67",
  "671",
  "672",
  "673",
  "674",
  "675",
  "678",
  "6781",
  "6782",
  "6783",
  "6788",
  "68",
  "681",
  "682",
  "683",
  "684",
  "685",
  "686",
  "687",
  "688",
  "69",
  "691",
  "694",
  "699",
  "7",
  "70",
  "701",
  "702",
  "704",
  "705",
  "707",
  "708",
  "709",
  "7091",
  "7092",
  "71",
  "711",
  "712",
  "714",
  "715",
  "717",
  "718",
  "719",
  "74",
  "741",
  "748",
  "75",
  "751",
  "752",
  "752.001",
  "753",
  "754",
  "755",
  "756",
  "757",
  "758",
  "76",
  "761",
  "7611",
  "7612",
  "762",
  "763",
  "764",
  "765",
  "766",
  "767",
  "768",
  "77",
  "773",
  "774",
  "775",
  "778",
  "7781",
  "7782",
  "7783",
  "7788",
  "78",
  "782",
  "783",
  "784",
  "785",
  "786",
  "787",
  "788",
];

export const DEFAULT_CHART_OF_ACCOUNTS = [
  // ═══════════════════════════════════════════════
  // ປະເພດ 1 - ຊັບສິນໝູນວຽນ (Asset)
  // ═══════════════════════════════════════════════
  {
    code: "1",
    parentCode: null,
    name: "ປະເພດ 1 - ບັນດາ ບັນຊີ ຊັບສິນໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "10",
    parentCode: "1",
    name:
      "ເງິນສົດໃນຄັງ, ເງິນຍ່ອຍ, ເງິນຝາກທະນາຄານ, ສະຖາບັນການເງິນ, ເງິນຝາກຄັງເງິນແຫ່ງຊາດ ແລະ ປະເພດດຽວກັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "101",
    parentCode: "10",
    name: "ເງິນສົດໃນຄັງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1011",
    parentCode: "101",
    name: "ເງິນສົດເປັນເງິນກີບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1012",
    parentCode: "101",
    name: "ເງິນສົດເປັນເງິນຕາຕ່າງປະເທດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1013",
    parentCode: "101",
    name: "ເງິນສົດຍ່ອຍ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1014",
    parentCode: "101",
    name: "ເງິນສົດກຳລັງນຳຝາກ - ທະນາຄານບໍ່ທັນໄດ້ຈົດເຂົ້າບັນຊີ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1017",
    parentCode: "101",
    name: "ລ່ວງໜ້າເງິນສົດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "102",
    parentCode: "10",
    name: "ເງິນຝາກທະນາຄານ, ສະຖາບັນການເງິນ ແລະ ສະຖາບັນທີ່ຄ້ານຄືກັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1021",
    parentCode: "102",
    name: "ເງິນຝາກທະນາຄານເປັນເງິນກີບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1022",
    parentCode: "102",
    name: "ເງິນຝາກທະນາຄານເປັນເງິນຕາຕ່າງປະເທດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1023",
    parentCode: "102",
    name: "ເງິນຝາກຄັງເງິນແຫ່ງຊາດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1024",
    parentCode: "102",
    name: "ເງິນຝາກສະຖາບັນການເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1028",
    parentCode: "102",
    name: "ດອກເບ້ຍ ຄິດໄລ່ - ຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "109",
    parentCode: "10",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນສົດຍ່ອຍ, ເງິນກຳລັງນຳຝາກທະນາຄານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1091",
    parentCode: "109",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນສົດຍ່ອຍ, ເງິນລ່ວງໜ້າ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1092",
    parentCode: "109",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນກຳລັງນຳຝາກທະນາຄານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "11",
    parentCode: "1",
    name:
      "ເຄື່ອງມືການເງິນ, ເຄື່ອງມືການເງິນໃນກຳມື ແລະ ເພື່ອຮຽກເກັບ, ຫຼັກຊັບລົງທຶນ ໄລຍະສັ້ນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "111",
    parentCode: "11",
    name: "ເຄື່ອງມືການເງິນຂັ້ນພື້ນຖານ - ຊັບສິນໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1111",
    parentCode: "111",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກການໃຫ້ເງິນກູ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1112",
    parentCode: "111",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກໃບຢັ້ງຢືນໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1113",
    parentCode: "111",
    name: "ຮຸ້ນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1114",
    parentCode: "111",
    name: "ພັນທະບັດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1116",
    parentCode: "111",
    name: "ເຄື່ອງມືການເງິນຂັ້ນພື້ນຖານອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1118",
    parentCode: "111",
    name: "ດອກເບ້ຍ ຄິດໄລ່ - ຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "112",
    parentCode: "11",
    name: "ເຄື່ອງມືການເງິນອື່ນໆ - ຊັບສິນໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "113",
    parentCode: "11",
    name: "ເຄື່ອງມືການເງິນໃນກຳມື ແລະ ເພື່ອຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1131",
    parentCode: "113",
    name: "ໃບຢັ້ງຢືນການຄ້າ ຮອດກຳນົດ ແລະ ພວມຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1132",
    parentCode: "113",
    name: "ໃບຢັ້ງຢືນການຄ້າ ມອບຂາຍຊຳລະ ຕາມອັດຕາຫຼຸດຜ່ອນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1133",
    parentCode: "113",
    name: "ແຊ໋ກໃນຄັງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1134",
    parentCode: "113",
    name: "ແຊ໋ກພວມຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1135",
    parentCode: "113",
    name: "ບັດສິນເຊື່ອທະນາຄານພວມຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1136",
    parentCode: "113",
    name: "ເອກະສານຢັ້ງຢືນມີຄ່າອື່ນໆພວມຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1139",
    parentCode: "113",
    name: "ແຊ໋ກທີ່ໄດ້ສັ່ງຈ່າຍ-ຜູ້ມີສິດຮັບເງິນ ບໍ່ທັນຮຽກເກັບນຳທະນາຄານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "114",
    parentCode: "11",
    name: "ຫຼັກຊັບລົງທຶນ ໄລຍະສັ້ນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1141",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ໃນຮຸ້ນຕົນເອງທີ່ໄດ້ຊື້ຄືນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1142",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ໃນຮຸ້ນຈົດທະບຽນຕະຫຼາດຫຼັກຊັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1143",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ໃນຮຸ້ນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1144",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ພັນທະບັດຄົງເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1145",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ພັນທະບັດຄົງເງິນ ຈົດທະບຽນໃນຕະຫຼາດຫຼັກຊັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1146",
    parentCode: "114",
    name: "ຫຼັກຊັບລົງທຶນ ພັນທະບັດຄົງເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1147",
    parentCode: "114",
    name: "ດອກເບ້ຍຄິດໄລ່ຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1148",
    parentCode: "114",
    name: "ຫຼັກຊັບໄລຍະສັ້ນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "119",
    parentCode: "11",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເຄື່ອງມືການເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1191",
    parentCode: "119",
    name: "ຄ່າສູນເສຍມູນຄ່າ - ເຄື່ອງມືການເງິນຂັ້ນພື້ນຖານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1192",
    parentCode: "119",
    name: "ຄ່າສູນເສຍມູນຄ່າ - ເຄື່ອງມືການເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1193",
    parentCode: "119",
    name: "ຄ່າສູນເສຍມູນຄ່າ - ເຄື່ອງມືການເງິນໃນກຳມື ແລະ ເພື່ອຮຽກເກັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1194",
    parentCode: "119",
    name: "ຄ່າສູນເສຍມູນຄ່າ - ຫຼັກຊັບລົງທຶນໄລຍະສັ້ນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "12",
    parentCode: "1",
    name: "ລູກຄ້າ ຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "121",
    parentCode: "12",
    name: "ລູກຄ້າ - ຄ່າສິນຄ້າ, ຜະລິດຕະພັນ, ບໍລິການ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1211",
    parentCode: "121",
    name: "ລູກຄ້າ - ຄ່າສິນຄ້າ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1212",
    parentCode: "121",
    name: "ລູກຄ້າ - ຄ່າຜະລິດຕະພັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1213",
    parentCode: "121",
    name: "ລູກຄ້າ - ຄ່າບໍລິການ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "122",
    parentCode: "12",
    name: "ລູກຄ້າ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1221",
    parentCode: "122",
    name: "ລູກຄ້າ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຮັບ ຄ່າສິນຄ້າ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1222",
    parentCode: "122",
    name: "ລູກຄ້າ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຮັບ ຄ່າຜະລິດຕະພັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1223",
    parentCode: "122",
    name: "ລູກຄ້າ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຮັບ ຄ່າບໍລິການ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "124",
    parentCode: "12",
    name: "ລູກຄ້າ - ໜີ້ຕ້ອງຮັບທວງຍາກ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "125",
    parentCode: "12",
    name:
      "ໜີ້ຕ້ອງຮັບ - ບ້ວງວຽກງານກໍ່ສ້າງ ຫຼື ບໍລິການທີ່ບໍ່ທັນໄດ້ ອອກໃບເກັບເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "126",
    parentCode: "12",
    name: "ລູກຄ້າ - ຂາຍຜະລິດຕະພັນ, ສິນຄ້າ ທີ່ບໍ່ທັນໄດ້ອອກໃບເກັບເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "129",
    parentCode: "12",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຂອງບັນຊີລູກໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "13",
    parentCode: "1",
    name: "ເຄື່ອງໃນສາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "131",
    parentCode: "13",
    name: "ວັດຖຸດິບ ແລະ ວັດຖຸປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1311",
    parentCode: "131",
    name: "ວັດຖຸດິບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1312",
    parentCode: "131",
    name: "ວັດຖຸປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "132",
    parentCode: "13",
    name: "ວັດຖຸອື່ນໆ ຮັບໃຊ້ການຜະລິດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1321",
    parentCode: "132",
    name: "ວັດຖຸຊົມໃຊ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1322",
    parentCode: "132",
    name: "ວັດຖຸປະກອບຊົມໃຊ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1323",
    parentCode: "132",
    name: "ເຄື່ອງຫຸ້ມຫໍ່ຖິ້ມເລີຍ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1324",
    parentCode: "132",
    name: "ເຄື່ອງຫຸ້ມຫໍ່ມັດຈຳ ຈຳແນກບໍ່ໄດ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "133",
    parentCode: "13",
    name: "ຜົນຜະລິດ ພວມປຸງແຕ່ງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1331",
    parentCode: "133",
    name: "ຜະລິດຕະພັນ ພວມຜະລິດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1332",
    parentCode: "133",
    name: "ວຽກງານພວມກໍ່ສ້າງ ພວມດຳເນີນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "134",
    parentCode: "13",
    name: "ການບໍລິການ ພວມດຳເນີນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1341",
    parentCode: "134",
    name: "ການຄົ້ນຄວ້າ ພວມດຳເນີນງານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1342",
    parentCode: "134",
    name: "ການໃຫ້ບໍລິການ ພວມດຳເນີນງານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "135",
    parentCode: "13",
    name: "ຊັບສິນຊີວະພາບ-ໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1351",
    parentCode: "135",
    name: "ສັດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1352",
    parentCode: "135",
    name: "ຕົ້ນໄມ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1358",
    parentCode: "135",
    name: "ຊັບສິນຊີວະພາບອື່ນໆ - ໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "136",
    parentCode: "13",
    name: "ຜະລິດຕະພັນ ໃນສາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1361",
    parentCode: "136",
    name: "ຜະລິດຕະພັນ ລະຫວ່າງກາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1365",
    parentCode: "136",
    name: "ຜະລິດຕະພັນ ສຳເລັດຮູບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1368",
    parentCode: "136",
    name: "ຜະລິດຕະພັນ ເສດເຫຼືອ ຫຼື ຜະລິດຕະພັນ ເກັບຄືນໄດ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "137",
    parentCode: "13",
    name: "ສິນຄ້າໃນສາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "138",
    parentCode: "13",
    name: "ເຄື່ອງໃນສາງ ຢູ່ທາງນອກ ( ພວມຢູ່ລະຫວ່າງທາງ ຫຼື ຝາກ ຫຼື ຄ້ຳປະກັນ )",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "139",
    parentCode: "13",
    name: "ຄ່າສູນເສຍມູນຄ່າເຄື່ອງໃນສາງ ແລະ ພວມຢູ່ລະຫວ່າງທາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1391",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ວັດຖຸດິບ ແລະ ວັດຖຸປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1392",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ວັດຖຸຮັບໃຊ້ໃນການຜະລິດອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1393",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຜົນຜະລິດພວມປຸງແຕ່ງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1394",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ການບໍລິການພວມດຳເນີນງານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1395",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສິນຊີວະພາບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1396",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຜະລິດຕະພັນໃນສາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1397",
    parentCode: "139",
    name: "ຄ່າສູນເສຍມູນຄ່າ ສິນຄ້າໃນສາງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1398",
    parentCode: "139",
    name: "ສ່ວນເສຍມູນຄ່າ ເຄື່ອງໃນສາງທາງນອກ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "14",
    parentCode: "1",
    name: "ລູກໜີ້ອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "141",
    parentCode: "14",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກການຂາຍ ຊັບສົມບັດຄົງທີ່",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "142",
    parentCode: "14",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກການຂາຍ ອະສັງຫາລິມະຊັບເພື່ອການລົງທຶນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "143",
    parentCode: "14",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກການຂາຍ ຊັບສິນຊີວະພາບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "145",
    parentCode: "14",
    name: "ໜີ້ຕ້ອງຮັບ ເຄື່ອງມືການເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "146",
    parentCode: "14",
    name: "ລາຍຈ່າຍ ຈ່າຍລ່ວງໜ້າ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "148",
    parentCode: "14",
    name: "ລູກໜີ້ອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "149",
    parentCode: "14",
    name: "ຄ່າສູນເສຍມູນຄ່າ ລູກໜີ້ອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "15",
    parentCode: "1",
    name: "ຜູ້ຖືຮຸ້ນ ຫຼື ບໍລິສັດໃນກຸ່ມ ຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "151",
    parentCode: "15",
    name: "ໜີ້ຕ້ອງຮັບ ບໍລິສັດໃນກຸ່ມ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "153",
    parentCode: "15",
    name: "ຂາຮຸ້ນ - ທຶນກຳລັງຈະປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "154",
    parentCode: "15",
    name: "ຂາຮຸ້ນ - ລ່ວງໜ້າເງິນປັນຜົນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "155",
    parentCode: "15",
    name: "ຂາຮຸ້ນ - ການເຄື່ອນໄຫວຮ່ວມກັນ ຫຼື ເປັນກຸ່ມ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "159",
    parentCode: "15",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຂອງບັນຊີກຸ່ມບໍລິສັດ ແລະ ຂາຮຸ້ນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "16",
    parentCode: "1",
    name: "ພະນັກງານ, ຜູ້ສະໜອງ, ອົງການປະກັນສັງຄົມ, ລັດ - ຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "160",
    parentCode: "16",
    name: "ພະນັກງານ - ຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1601",
    parentCode: "160",
    name: "ພະນັກງານ - ເງິນລ່ວງໜ້າ ແລະ ຈ່າຍກ່ອນສ່ວນໜຶ່ງທີ່ໄດ້ ອະນຸມັດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1602",
    parentCode: "160",
    name: "ພະນັກງານ - ລ່ວງໜ້າເງິນບຳເນັດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1608",
    parentCode: "160",
    name: "ພະນັກງານ - ໜີ້ຕ້ອງຮັບອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "161",
    parentCode: "16",
    name: "ຜູ້ສະໜອງ - ຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1611",
    parentCode: "161",
    name: "ເງິນຈ່າຍລ່ວງໜ້າ ໃຫ້ຜູ້ສະໜອງ ແລະ ເງິນຈ່າຍກ່ອນສ່ວນໜຶ່ງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1612",
    parentCode: "161",
    name: "ສ່ວນຫຼຸດຕ້ອງຮັບ ຈາກຜູ້ສະໜອງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1613",
    parentCode: "161",
    name: "ຜູ້ສະໜອງ - ໜີ້ຕ້ອງຮັບ ບ້ວງເຄື່ອງຫຸ້ມຫໍ່ ທີ່ຕ້ອງສົ່ງຄືນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1618",
    parentCode: "161",
    name: "ໜີ້ຕ້ອງຮັບອື່ນໆ ນຳຜູ້ສະໜອງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "162",
    parentCode: "16",
    name: "ອົງການປະກັນສັງຄົມ, ລາຍຈ່າຍ ຈ່າຍລ່ວງໜ້າ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "163",
    parentCode: "16",
    name: "ລັດ - ເງິນຊ່ວຍໜູນຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "164",
    parentCode: "16",
    name: "ລັດ - ອາກອນກຳໄລ ຈ່າຍລ່ວງໜ້າ ຫຼື ຈ່າຍເກີນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "165",
    parentCode: "16",
    name: "ລັດ - ອມພ ທີ່ສາມາດຫັກໄດ້ ສຳລັບ ຊັບສົມບັດຄົງທີ່",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "166",
    parentCode: "16",
    name: "ລັດ - ອມພ ທີ່ສາມາດຫັກໄດ້ ສຳລັບ ສິນຄ້າ, ການບໍລິການ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "167",
    parentCode: "16",
    name: "ລັດ - ອມພ ຍົກໄປຫັກຕໍ່ ຫຼື ສິນເຊື່ອ ອມພ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "168",
    parentCode: "16",
    name: "ລັດ - ອມພ ບ້ວງໃບເກັບເງິນບໍ່ທັນມາຮອດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "169",
    parentCode: "16",
    name: "ຄ່າສູນເສຍມູນຄ່າ ພະນັກງານ, ຜູ້ສະໜອງ, ອົງການປະກັນສັງຄົມ ແລະ ລັດຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1690",
    parentCode: "169",
    name: "ຄ່າສູນເສຍມູນຄ່າ ພະນັກງານຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1691",
    parentCode: "169",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຜູ້ສະໜອງຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1692",
    parentCode: "169",
    name: "ຄ່າສູນເສຍມູນຄ່າ ອົງການປະກັນສັງຄົມຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "1693",
    parentCode: "169",
    name: "ຄ່າສູນເສຍມູນຄ່າ ລັດຕິດໜີ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 2 - ຊັບສິນບໍ່ໝູນວຽນ (Asset)
  // ═══════════════════════════════════════════════
  {
    code: "2",
    parentCode: null,
    name: "ປະເພດ 2 - ບັນດາ ບັນຊີ ຊັບສິນບໍ່ໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "20",
    parentCode: "2",
    name: "ຊັບສົມບັດຄົງທີ່ການເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "201",
    parentCode: "20",
    name: "ເງິນລົງທຶນ ແນ່ໃສ່ເພື່ອຂາຍອອກ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "202",
    parentCode: "20",
    name: "ເງິນລົງທຶນ ຖືໄວ້ຈົນຄົບກຳນົດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "203",
    parentCode: "20",
    name: "ເງິນລົງທຶນ ໃນພັນທະບັດລັດຖະບານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "204",
    parentCode: "20",
    name: "ເງິນໃຫ້ກູ້ຢືມ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "205",
    parentCode: "20",
    name: "ເງິນວາງ ແລະ ເງິນຄ້ຳປະກັນ ທີ່ໄດ້ຈ່າຍ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "206",
    parentCode: "20",
    name: "ເງິນລົງທຶນ ໃນອະສັງຫາລິມະຊັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "207",
    parentCode: "20",
    name: "ດອກເບັ້ຍຄິດໄລ່ ຕ້ອງຮັບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "208",
    parentCode: "20",
    name: "ໜີ້ຕ້ອງຮັບຄົງທີ່ການເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "209",
    parentCode: "20",
    name: "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງໃບຢັ້ງຢືນຊັບຄົງທີ່ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "21",
    parentCode: "2",
    name: "ເງິນລົງທຶນ ແລະ ໜີ້ຕ້ອງຮັບ ທີ່ຕິດພັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "210",
    parentCode: "21",
    name: "ເງິນລົງທຶນ ບໍລິສັດໃນເຄື່ອ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "211",
    parentCode: "21",
    name: "ເງິນລົງທຶນ ໃນບໍລິສັດຮ່ວມທຶນ (ວິສາຫະກິດປະສົມ)",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "212",
    parentCode: "21",
    name: "ເງິນລົງທຶນ ໃນບໍລິສັດຄວບຄຸມຮ່ວມກັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "213",
    parentCode: "21",
    name: "ເງິນໃຫ້ ບໍລິສັດໃນກຸ່ມ (ໃນເຄືອ) ກູ້ຢືມ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "214",
    parentCode: "21",
    name: "ພູດສ່ວນຮຸ້ນໃນວິສາຫະກິດ ທີ່ຊື້ຊັບສິນສຸດທິ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "216",
    parentCode: "21",
    name: "ໜີ້ຕ້ອງຮັບອື່ນໆ ທີ່ຕິດພັນກັບການຮ່ວມປະກອບທຶນ ບໍລິສັດໃນເຄື່ອ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "217",
    parentCode: "21",
    name: "ໜີ້ຕ້ອງຮັບອື່ນໆ ທີ່ຕິດພັນກັບ ບໍລິສັດ ຮຸ້ນສ່ວນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "218",
    parentCode: "21",
    name:
      "ໜີ້ຕ້ອງຮັບອື່ນໆ ທີ່ຕິດພັນກັບ ເງິນລົງທຶນໃນຊັບສິນສຸດທິ ຕາມມູນຄ່າຍຸຕິທຳ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "219",
    parentCode: "21",
    name: "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງຮ່ວມປະກອບທຶນ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2190",
    parentCode: "219",
    name:
      "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງຮ່ວມປະກອບທຶນ ບໍລິສັດໃນເຄືອ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2191",
    parentCode: "219",
    name:
      "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງຮ່ວມປະກອບທຶນ ໃນບໍລິສັດຮ່ວມ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2192",
    parentCode: "219",
    name:
      "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງຮ່ວມປະກອບທຶນ ໃນບໍລິສັດຄວບຄຸມຮ່ວມກັນ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2194",
    parentCode: "219",
    name:
      "ເງິນທີ່ຕ້ອງຖອກຕື່ມ ບ້ວງເງິນລົງທຶນໃນຊັບສິນສຸດທິ ທີ່ຍັງບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "22",
    parentCode: "2",
    name: "ຊັບສົມບັດຄົງທີ່ ເຊົ່າສິນເຊື່ອ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "221",
    parentCode: "22",
    name: "ເຊົ່າສິນເຊື່ອ - ສິດນຳໃຊ້ທີ່ດິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "222",
    parentCode: "22",
    name: "ເຊົ່າສິນເຊື່ອ - ສິ່ງປຸກສ້າງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "223",
    parentCode: "22",
    name: "ເຊົ່າສິນເຊື່ອ - ເຄື່ອງຈັກ ແລະ ອຸປະກອນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "224",
    parentCode: "22",
    name: "ເຊົ່າສິນເຊື່ອ - ພາຫະນະ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "225",
    parentCode: "22",
    name: "ເຊົ່າສິນເຊື່ອ - ຊັບສົມບັດຄົງທີ່ອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "226",
    parentCode: "22",
    name: "ໜີ້ຕ້ອງຮັບ ຈາກການໃຫ້ເຊົ່າສິນເຊື່ອ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "23",
    parentCode: "2",
    name: "ຊັບສົມບັດຄົງທີ່ ພວມຊື້ ຫຼື ພວມຜະລິດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "231",
    parentCode: "23",
    name: "ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ ພວມຊື້ ຫຼື ພວມຜະລິດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "232",
    parentCode: "23",
    name: "ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ ພວມຊື້ ຫຼື ພວມຜະລິດ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "237",
    parentCode: "23",
    name: "ເງິນລ່ວງໜ້າ ແລະ ຈ່າຍສັ່ງຊື້ ຊັບສົມບັດຄົງທີ່ ການເງິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "238",
    parentCode: "23",
    name:
      "ເງິນລ່ວງໜ້າ ແລະ ຈ່າຍສັ່ງຊື້ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ ແລະ ບໍ່ມີຕົວຕົນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2381",
    parentCode: "238",
    name: "ເງິນລ່ວງໜ້າ ແລະ ຈ່າຍສັ່ງຊື້ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2382",
    parentCode: "238",
    name: "ເງິນລ່ວງໜ້າ ແລະ ຈ່າຍສັ່ງຊື້ ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "24",
    parentCode: "2",
    name: "ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ, ບໍ່ມີຕົວຕົນ ແລະ ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "241",
    parentCode: "24",
    name: "ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2411",
    parentCode: "241",
    name: "ເຟີນີເຈີ ແລະ ອຸປະກອນສຳນັກງານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2412",
    parentCode: "241",
    name: "ສິ່ງປຸກສ້າງ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2413",
    parentCode: "241",
    name: "ເຄື່ອງຈັກ ແລະ ອຸປະກອນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2414",
    parentCode: "241",
    name: "ພາຫະນະ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2417",
    parentCode: "241",
    name: "ຊັບສົມບັດຄົງທີ່ ປ່ຽນແທນກັນໄດ້",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2418",
    parentCode: "241",
    name: "ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "242",
    parentCode: "24",
    name: "ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2420",
    parentCode: "242",
    name: "ສິດນຳໃຊ້ທີ່ດິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2421",
    parentCode: "242",
    name: "ຄ່າໃຊ້ຈ່າຍໃນການພັດທະນາ ທີ່ຈົດເປັນມູນຄ່າຄົງທີ່",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2422",
    parentCode: "242",
    name: "ໂປຣແກມ, ສິດນຳໃຊ້ ແລະ ຊັບສິນທີ່ຄ້າຍຄືກັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2423",
    parentCode: "242",
    name: "ສິດທິສຳປະທານ ແລະ ສິດທິປະເພດດຽວກັນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2427",
    parentCode: "242",
    name: "ຊັບສົມບັດຮ້ານຄ້າ (ຄ່ານິຍົມ)",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2428",
    parentCode: "242",
    name: "ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນອື່ນໆ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "243",
    parentCode: "24",
    name: "ຊັບສົມບັດຄົງທີ່ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2430",
    parentCode: "243",
    name: "ສິດນຳໃຊ້ທີ່ດິນ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2431",
    parentCode: "243",
    name: "ເຟີນີເຈີ ແລະ ອຸປະກອນສຳນັກງານ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2432",
    parentCode: "243",
    name: "ສິ່ງປຸກສ້າງ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2433",
    parentCode: "243",
    name: "ເຄື່ອງຈັກ ແລະ ອຸປະກອນ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2434",
    parentCode: "243",
    name: "ພາຫະນະ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "2438",
    parentCode: "243",
    name: "ຊັບສົມບັດຄົງທີ່ອື່ນໆ - ສຳປະທານ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "25",
    parentCode: "2",
    name: "ຊັບສິນຊີວະພາບ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "251",
    parentCode: "25",
    name: "ສັດລ້ຽງ (ພໍ່ແມ່ພັນ)",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "252",
    parentCode: "25",
    name: "ຕົ້ນໄມ້ (ຕົ້ນໄມ້ກິນໝາກ ແລະ ສວນປູກຝັງ)",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "258",
    parentCode: "25",
    name: "ຊັບສິນຊີວະພາບອື່ນໆ-ບໍ່ໝູນວຽນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "27",
    parentCode: "2",
    name: "ເງິນເຍື້ອນຊຳລະ ນອກຮອບວຽນທຸລະກິດ - ຊັບສິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "271",
    parentCode: "27",
    name: "ອາກອນເຍື້ອນຊຳລະ - ຊັບສິນ",
    type: "asset",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "28",
    parentCode: "2",
    name: "ຄ່າຫຼຸ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "282",
    parentCode: "28",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ເຊົ່າສິນເຊື່ອ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "284",
    parentCode: "28",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ, ບໍ່ມີຕົວຕົນ ແລະ ສຳປະທານ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2841",
    parentCode: "284",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2842",
    parentCode: "284",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2843",
    parentCode: "284",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ສຳປະທານ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "285",
    parentCode: "28",
    name: "ຄ່າຫຼູ້ຍຫ້ຽນ ຊັບສິນຊີວະພາດ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "29",
    parentCode: "2",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "290",
    parentCode: "29",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ການເງິນອື່ນໆ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "291",
    parentCode: "29",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນລົງທຶນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2910",
    parentCode: "291",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນລົງທຶນ ບໍລິສັດໃນເຄື່ອ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2911",
    parentCode: "291",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນລົງທຶນ ໃນບໍລິສັດຮ່ວມ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2912",
    parentCode: "291",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນລົງທຶນ ໃນບໍລິສັດຄວບຄຸມຮ່ວມກັນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2914",
    parentCode: "291",
    name: "ຄ່າສູນເສຍມູນຄ່າ ເງິນລົງທຶນ ໃນຊັບສິນຕາມມູນຄ່າທຽບເທົ່າ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "292",
    parentCode: "29",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ເຊົ່າສິນເຊື່ອ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "294",
    parentCode: "29",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ, ບໍ່ມີຕົວຕົນ ແລະ ສຳປະທານ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2941",
    parentCode: "294",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2942",
    parentCode: "294",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "2943",
    parentCode: "294",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ສຳປະທານ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "295",
    parentCode: "29",
    name: "ຄ່າສູນເສຍມູນຄ່າ ຊັບສິນຊີວະພາບ",
    type: "asset",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 3 - ທຶນ (Equity)
  // ═══════════════════════════════════════════════
  {
    code: "3",
    parentCode: null,
    name: "ປະເພດ 3 - ບັນດາບັນຊີ ທຶນ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "30",
    parentCode: "3",
    name: "ທຶນ, ບັນຊີ ປະເພດດຽວກັນ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "301",
    parentCode: "30",
    name: "ທຶນຈົດທະບຽນ - ບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "302",
    parentCode: "30",
    name: "ທຶນຈົດທະບຽນຮຽກໃຫ້ປະກອບ - ບໍ່ທັນຖອກ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "303",
    parentCode: "30",
    name: "ທຶນຈົດທະບຽນ - ຖອກແລ້ວ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "304",
    parentCode: "30",
    name: "ສ່ວນເພີ່ມມູນຄ່າຮຸ້ນ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "308",
    parentCode: "30",
    name: "ບັນຊີທຶນຂອງເຈົ້າຂອງທຸລະກິດ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "309",
    parentCode: "30",
    name: "ຜູ້ຖືຮຸ້ນ ທຶນຈົດທະບຽນທີ່ບໍ່ທັນຮຽກໃຫ້ປະກອບ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "31",
    parentCode: "3",
    name: "ຄັງສຳຮອງ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "311",
    parentCode: "31",
    name: "ຄັງສຳຮອງຕາມລະບຽບການ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "312",
    parentCode: "31",
    name: "ຄັງສຳຮອງອື່ນໆ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "32",
    parentCode: "3",
    name: "ຍອດຍົກມາ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "321",
    parentCode: "32",
    name: "ກຳໄລຍົກມາ (ເຫຼືອມີ)",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "329",
    parentCode: "32",
    name: "ຂາດທຶນຍົກມາ (ເຫຼືອໜີ້)",
    type: "equity",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "329.2023",
    parentCode: "329",
    name: "ຂາດທຶນຍົກມາ 2023",
    type: "equity",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "329.2024",
    parentCode: "329",
    name: "ຂາດທຶນຍົກມາ 2024",
    type: "equity",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "33",
    parentCode: "3",
    name: "ຜົນໄດ້ຮັບໃນປີ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "331",
    parentCode: "33",
    name: "ກຳໄລພາຍໃນປີ",
    type: "equity",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "339",
    parentCode: "33",
    name: "ຂາດທຶນພາຍໃນປີ",
    type: "equity",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 4 - ໜີ້ສິນ (Liability)
  // ═══════════════════════════════════════════════
  {
    code: "4",
    parentCode: null,
    name: "ປະເພດ 4 - ບັນດາ ບັນຊີ ໜີ້ສິນ ທີ່ຕິດພັນກັບພາກສ່ວນອື່ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "40",
    parentCode: "4",
    name: "ຜູ້ສະໜອງ ເປັນເຈົ້າໜີ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "401",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ສິນຄ້າ, ວັດຖຸ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "402",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ການບໍລິການ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "403",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ສິນຄ້າ ແລະ ການບໍລິການ ໃບຢັ້ງຢືນການຄ້າຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4031",
    parentCode: "403",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ສິນຄ້າ, ວັດຖຸ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4032",
    parentCode: "403",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ການບໍລິການ - ໃບຢັ້ງຢືນການຄ້າຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "404",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ຊັບສົມບັດຄົງທີ່",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4041",
    parentCode: "404",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ - ຊັບສົມບັດຄົງທີ່ ການເງິນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4042",
    parentCode: "404",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ - ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4043",
    parentCode: "404",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ - ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "405",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ຊັບສົມບັດຄົງທີ່ ໃບຢັ້ງຢືນການຄ້າຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "408",
    parentCode: "40",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ໃບເກັບເງິນບໍ່ທັນມາຮອດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "41",
    parentCode: "4",
    name: "ເຄື່ອງມືການເງິນ - ໜີ້ສິນໝູນວຽນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "411",
    parentCode: "41",
    name: "ເງິນເບີກເກີນບັນຊີ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "412",
    parentCode: "41",
    name: "ເງິນກູ້ຢືມ ນຳສະຖາບັນການເງິນ ໄລຍະສັ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "413",
    parentCode: "41",
    name: "ພັນທະບັດກູ້ຢືມໄລຍະສັ້ນ ທີ່ໄດ້ອອກ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "417",
    parentCode: "41",
    name: "ດອກເບ້ຍ ເຄື່ອງມືການເງິນ ຄິດໄລ່ຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "418",
    parentCode: "41",
    name: "ໜີ້ຕ້ອງສົ່ງ ເຄື່ອງມືການເງິນອື່ນໆ ໄລຍະສັ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "42",
    parentCode: "4",
    name: "ພະນັກງານ, ລູກຄ້າ, ອົງການປະກັນສັງຄົມ ເປັນເຈົ້າໜີ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "420",
    parentCode: "42",
    name: "ໜີ້ຕ້ອງສົ່ງ ພະນັກງານ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4201",
    parentCode: "420",
    name: "ພະນັກງານ - ຄ່າທົດແທນແຮງງານຕ້ອງສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4202",
    parentCode: "420",
    name: "ພະນັກງານ - ເງິນບຳເນັດ ແລະ ຍ້ອງຍໍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4203",
    parentCode: "420",
    name: "ພະນັກງານ - ເງິນນະໂຍບາຍພັກຜ່ອນ ແລະ ສະຫວັດດີການຕ້ອງສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4204",
    parentCode: "420",
    name: "ພະນັກງານ - ເງິນນະໂຍບາຍພັກຜ່ອນ ທີ່ໄດ້ຫັກໄວ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4205",
    parentCode: "420",
    name: "ໜີ້ຕ້ອງສົ່ງ ບ້ວງເງິນສົມທົບ ຜົນປະໂຫຍດພະນັກງານ ຕາມກົດລະບຽບທີ່ກຳນົດໄວ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4206",
    parentCode: "420",
    name: "ພະນັກງານ - ເງິນມັດຈຳທີ່ໄດ້ຮັບ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4207",
    parentCode: "420",
    name: "ພະນັກງານ - ເງິນຕັດໄວ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4208",
    parentCode: "420",
    name: "ພະນັກງານ - ຄ່າທົດແທນອື່ນໆຕ້ອງສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "421",
    parentCode: "42",
    name: "ລູກຄ້າ ເປັນເຈົ້າໜີ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4211",
    parentCode: "421",
    name: "ລູກຄ້າ - ລາຍຮັບຮັບລ່ວງໜ້າ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4212",
    parentCode: "421",
    name: "ລູກຄ້າ - ໜີ້ຕ້ອງສົ່ງບ້ວງເຄື່ອງຫຸ້ມຫໍ່ ທີ່ໄດ້ມັດຈຳ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4213",
    parentCode: "421",
    name: "ລູກຄ້າ - ສ່ວນຫຼຸດຕ້ອງຜ່ອນ, ເງິນສົ່ງຄືນຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4218",
    parentCode: "421",
    name: "ລູກຄ້າ - ເງິນສົ່ງຄືນອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "422",
    parentCode: "42",
    name: "ໜີ້ຕ້ອງສົ່ງ ອົງການປະກັນສັງຄົມ ແລະ ບັນຊີພົວພັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4221",
    parentCode: "422",
    name: "ອົງການປະກັນສັງຄົມ - (ບ້ວງລູກຈ້າງ)",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4222",
    parentCode: "422",
    name: "ອົງການປະກັນສັງຄົມ - (ບ້ວງນາຍຈ້າງ)",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4226",
    parentCode: "422",
    name: "ອົງການປະກັນສັງຄົມ, ລາຍຈ່າຍ ຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4228",
    parentCode: "422",
    name: "ອົງການຈັດຕັ້ງ ສາກົນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "43",
    parentCode: "4",
    name: "ໜີ້ຕ້ອງສົ່ງ ພາສີ-ອາກອນ ຕ່າງໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "430",
    parentCode: "43",
    name: "ລັດ - ອາກອນ ເກັບຈາກພາກສ່ວນອື່ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "430.1",
    parentCode: "430",
    name: "ອາກອນເງິນເດືອນຕ້ອງສົ່ງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "431",
    parentCode: "43",
    name: "ລັດ - ອາກອນກຳໄລ ຕ້ອງມອບ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "432",
    parentCode: "43",
    name: "ລັດ - ອມພ ທີ່ເກັບໄດ້ ຫຼື ອມພ ສົ້ນອອກ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "433",
    parentCode: "43",
    name: "ລັດ - ອມພ ທີ່ຕ້ອງມອບ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "434",
    parentCode: "43",
    name: "ລັດ - ອມພ ບ້ວງໃບເກັບເງິນຕ້ອງອອກ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "435",
    parentCode: "43",
    name: "ລັດ - ອມພ ບ້ວງອື່ນໆ ລໍຖ້າສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "436",
    parentCode: "43",
    name: "ລັດ - ລາຍການເຄື່ອນໄຫວສະເພາະກັບລັດ ແລະ ອົງການອື່ນໆຂອງລັດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "437",
    parentCode: "43",
    name: "ລັດ - ອາກອນອື່ນໆ ແລະ ລາຍຈ່າຍປະເພດດຽວກັນ ຕ້ອງມອບ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "438",
    parentCode: "43",
    name: "ລັດ - ລາຍຈ່າຍອື່ນໆຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "44",
    parentCode: "4",
    name: "ເຈົ້າໜີ້ອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "441",
    parentCode: "44",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ການລົງທຶນໄລຍະສັ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "442",
    parentCode: "44",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ຊັບສິນຊີວະພາບ ໄລຍະສັ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "443",
    parentCode: "44",
    name: "ໜີ້ຕ້ອງສົ່ງ ຜູ້ສະໜອງ ສັນຍາເຊົ່າສິນເຊື່ອ ໄລຍະສັ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "447",
    parentCode: "44",
    name: "ລາຍຮັບ ຮັບລ່ວງໜ້າ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "448",
    parentCode: "44",
    name: "ເຈົ້າໜີ້ອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "45",
    parentCode: "4",
    name: "ຜູ້ຖືຮຸ້ນ ແລະ ຄູ່ສັນຍາ ເປັນເຈົ້າໜີ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "451",
    parentCode: "45",
    name: "ການເຄື່ອນໄຫວບໍລິສັດໃນກຸ່ມ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "452",
    parentCode: "45",
    name: "ຂາຮຸ້ນ-ບັນຊີເງິນຝາກກະແສລາຍວັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "453",
    parentCode: "45",
    name: "ຂາຮຸ້ນ-ການເຄື່ອນໄຫວ ກ່ຽວກັບທຶນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "454",
    parentCode: "45",
    name: "ຂາຮຸ້ນ-ເງິນປັນຜົນ ຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "455",
    parentCode: "45",
    name: "ຂາຮຸ້ນ-ການເຄື່ອນໄຫວຮ່ວມກັນ ຫຼື ເປັນກຸ່ມ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "456",
    parentCode: "45",
    name: "ຂາຮຸ້ນ-ທຶນທີ່ຕ້ອງທົດແທນຄືນ ຫຼື ຊຳລະສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "457",
    parentCode: "45",
    name: "ຂາຮຸ້ນ - ລາຍຮັບໆລ່ວງໜ້າ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "458",
    parentCode: "45",
    name: "ຜູ້ຖືຮຸ້ນ ແລະ ຄູ່ສັນຍາອື່ນໆ ເປັນເຈົ້າໜີ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "46",
    parentCode: "4",
    name: "ເງິນແຮ ໜີ້ສິນໝູນວຽນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "461",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບການດຳເນີນຄະດີ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "462",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບເບ້ຍບຳນານ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "463",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບຕຳແໜ່ງງານອື່ນ-ຜົນປະໂຫຍດຂອງພະນັກງານ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "464",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບການປັບປຸງໂຄງສ້າງ ວິສາຫະກິດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "465",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບການຄ້ຳປະກັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "466",
    parentCode: "46",
    name: "ເງິນແຮ ສຳລັບສັນຍາທີ່ສ້າງພາລະ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "468",
    parentCode: "46",
    name: "ເງິນແຮ ໜີ້ສິນໝູນວຽນອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "47",
    parentCode: "4",
    name: "ເຄື່ອງມືການເງິນ, ເງິນກູ້ຢືມ ແລະ ໜີ້ຕ້ອງສົ່ງປະເພດດຽວກັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "471",
    parentCode: "47",
    name: "ພັນທະບັດ ປ່ຽນເປັນຮຸ້ນໄດ້",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "472",
    parentCode: "47",
    name: "ພັນທະບັດອື່ນໆ ທີ່ໄດ້ອອກ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "473",
    parentCode: "47",
    name: "ເງິນກູ້ຢືມ ນຳສະຖາບັນສິນເຊື່ອ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "474",
    parentCode: "47",
    name: "ເງິນວາງ ແລະ ເງິນຄ້ຳປະກັນ ທີ່ໄດ້ຮັບ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "475",
    parentCode: "47",
    name: "ໜີ້ຕ້ອງສົ່ງ ສັນຍາເຊົ່າສິນເຊື່ອ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "477",
    parentCode: "47",
    name: "ດອກເບ້ຍຄິດໄລ່ ເຖິງກຳນົດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "478",
    parentCode: "47",
    name: "ເຄື່ອງມືການເງິນ ແລະ ໜີ້ຕ້ອງສົ່ງອື່ນໆ ປະເພດດຽວກັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "48",
    parentCode: "4",
    name:
      "ໜີ້ຕ້ອງສົ່ງ ທີ່ຕິດພັນກັບການຮ່ວມປະກອບທຶນ, ເງິນຊ່ວຍໜູນ, ເງິນເຍື້ອນຊຳລະ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "481",
    parentCode: "48",
    name: "ໜີ້ຕ້ອງສົ່ງ ທີ່ຕິດພັນກັບການຮ່ວມປະກອບທຶນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4811",
    parentCode: "481",
    name: "ໜີ້ຕ້ອງສົ່ງ - ການຮ່ວມປະກອບທຶນ ໃນກຸ່ມບໍລິສັດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4812",
    parentCode: "481",
    name: "ໜີ້ຕ້ອງສົ່ງ - ການຮ່ວມປະກອບທຶນ ນອກກຸ່ມບໍລິສັດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4813",
    parentCode: "481",
    name: "ໜີ້ຕ້ອງສົ່ງ - ທີ່ຕິດພັນກັບ ບໍລິສັດຮ່ວມປະກອບທຶນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4816",
    parentCode: "481",
    name: "ດອກເບັ້ຍຄິດໄລ່ ຕ້ອງຈ່າຍ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4818",
    parentCode: "481",
    name: "ໜີ້ຕ້ອງສົ່ງອື່ນໆ ທີ່ຕິດພັນກັບການຮ່ວມປະກອບທຶນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "482",
    parentCode: "48",
    name: "ເງິນຊ່ວຍໜູນຂອງລັດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4821",
    parentCode: "482",
    name: "ເງິນຊ່ວຍໜູນ ປະກອບພາຫະນະ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4822",
    parentCode: "482",
    name: "ເງິນຊ່ວຍໜູນ ລົງທຶນອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4829",
    parentCode: "482",
    name: "ພູດສ່ວນເງິນຊ່ວຍໜູນຂອງລັດ ຈົດເຂົ້າບັນຊີຜົນໄດ້ຮັບໃນປີ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "483",
    parentCode: "48",
    name: "ອາກອນເຍື້ອນຊຳລະ - ໜີ້ສິນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "49",
    parentCode: "4",
    name: "ເງິນແຮ ເພື່ອໜີ້ສິນບໍ່ໝູນວຽນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "491",
    parentCode: "49",
    name: "ເງິນແຮ ສຳລັບພະນັກງານ ໄລຍະຍາວ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4911",
    parentCode: "491",
    name: "ເງິນແຮ ເພື່ອການປິ່ນປົວ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4912",
    parentCode: "491",
    name: "ເງິນແຮ ເພື່ອການພັກຜ່ອນປະຈຳປີ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4913",
    parentCode: "491",
    name: "ເງິນແຮ ເພື່ອການເຮັດວຽກງານໄລຍະຍາວ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4914",
    parentCode: "491",
    name: "ເງິນແຮ ສຳລັບເບ້ຍບຳນານ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "4915",
    parentCode: "491",
    name: "ເງິນແຮ ສຳລັບຜົນປະໂຫຍດຂອງພະນັກງານ ໃນເວລາສິ້ນສຸດການຈ້າງງານ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "492",
    parentCode: "49",
    name: "ເງິນແຮ ອາກອນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "493",
    parentCode: "49",
    name: "ເງິນແຮ ສຳລັບການດຳເນີນຄະດີ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "494",
    parentCode: "49",
    name: "ເງິນແຮ ສຳລັບການປັບປຸງໂຄງສ້າງ ວິສາຫະກິດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "495",
    parentCode: "49",
    name: "ເງິນແຮ ສຳລັບການຄ້ຳປະກັນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "496",
    parentCode: "49",
    name: "ເງິນແຮ ເພື່ອການຟື້ນຟູ, ຮື້ຖອນ ແລະ ປົວແປງຄືນໃໝ່",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "497",
    parentCode: "49",
    name: "ເງິນແຮ ເພື່ອການຂາດທຶນຈາກລາຄາຮຸ້ນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "498",
    parentCode: "49",
    name: "ເງິນແຮ ໜີ້ສິນບໍ່ໝູນວຽນອື່ນໆ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 5 - ບັນຊີພົວພັນ (Liability)
  // ═══════════════════════════════════════════════
  {
    code: "5",
    parentCode: null,
    name: "ປະເພດ 5 - ບັນດາ ບັນຊີ ພົວພັນ, ລໍຖ້າສະສາງ ແລະ ບັນຊີ ໂອນພາຍໃນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "50",
    parentCode: "5",
    name: "ບັນຊີ ພົວພັນ ລະຫວ່າງ ກົມກອງພາຍໃນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "501",
    parentCode: "50",
    name: "ບັນຊີພົວພັນ ລະຫ່ວາງ ກົມກອງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "506",
    parentCode: "50",
    name: "ສິນຄ້າ ແລະ ການບໍລິການ ແລກປ່ຽນລະຫວ່າງກົມກອງ (ລາຍຈ່າຍ)",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "507",
    parentCode: "50",
    name: "ສິນຄ້າ ແລະ ການບໍລິການ ແລກປ່ຽນລະຫວ່າງກົມກອງ (ລາຍຮັບ)",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "51",
    parentCode: "5",
    name: "ບັນຊີ ລໍຖ້າສະສາງ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "511",
    parentCode: "51",
    name: "ບັນຊີຕັດແບ່ງລາຍຈ່າຍໃນປີ ເປັນໄລຍະ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "512",
    parentCode: "51",
    name: "ບັນຊີຕັດແບ່ງລາຍຮັບໃນປີ ເປັນໄລຍະ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "518",
    parentCode: "51",
    name: "ບັນຊີ ຂ້າມຜ່ານ ຫຼື ລໍຖ້າ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "58",
    parentCode: "5",
    name: "ໂອນເງິນພາຍໃນ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "581",
    parentCode: "58",
    name: "ມອບເງິນສົດ ເຂົ້າທະນາຄານ ຫຼື ຄັງເງິນແຫ່ງຊາດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "582",
    parentCode: "58",
    name: "ຖອນເງິນຝາກທະນາຄານ ຫຼື ຄັງເງິນແຫ່ງຊາດ ເຂົ້າຄັງເງິນສົດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "583",
    parentCode: "58",
    name: "ໂອນເງິນຝາກທະນາຄານ ຫາ ເງິນຝາກທະນາຄານ ຫຼື ຄັງເງິນແຫ່ງຊາດ",
    type: "liability",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 6 - ລາຍຈ່າຍ (Expense)
  // ═══════════════════════════════════════════════
  {
    code: "6",
    parentCode: null,
    name: "ປະເພດ 6 - ບັນດາ ບັນຊີ ລາຍຈ່າຍ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "60",
    parentCode: "6",
    name: "ຊື້ທີ່ໄດ້ຊົມໃຊ້, ຕົ້ນທຶນທີ່ໄດ້ຂາຍອອກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "601",
    parentCode: "60",
    name: "ວັດຖຸດິບ, ວັດຖຸປະກອບ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "602",
    parentCode: "60",
    name: "ວັດຖຸຮັບໃຊ້ການຜະລິດ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "603",
    parentCode: "60",
    name: "ຜະລິດຕະພັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "604",
    parentCode: "60",
    name: "ການຄົ້ນຄວ້າ ແລະ ການບໍລິການ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "605",
    parentCode: "60",
    name: "ຊັບສິນ ຊີວະພາບ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "606",
    parentCode: "60",
    name: "ຊື້ວັດຖຸ ແລະ ເຄື່ອງໃຊ້ຫ້ອງການ ທີ່ບໍ່ເອົາເຂົ້າສາງ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "607",
    parentCode: "60",
    name: "ສິນຄ້າ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຂາຍ",
  },
  {
    code: "609",
    parentCode: "60",
    name: "ສ່ວນຫຼຸດຕ່າງໆ ທີ່ໄດ້ຮັບຈາກການຊື້",
    type: "expense",
    normalSide: "Cr",
    category: "ຕົ້ນທຸນຂາຍ",
  },

  {
    code: "61",
    parentCode: "6",
    name: "ບໍລິການຈາກທາງນອກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "611",
    parentCode: "61",
    name: "ຈ້າງທາງນອກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "612",
    parentCode: "61",
    name: "ຄ່າເຊົ່າ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "613",
    parentCode: "61",
    name: "ຄ່າທຳນຽມ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "614",
    parentCode: "61",
    name: "ຄ່າບົວລະບັດ, ບຳລຸງຮັກສາ ແລະ ສ້ອມແປງ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "615",
    parentCode: "61",
    name: "ຄ່າທຳນຽມປະກັນໄພ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "616",
    parentCode: "61",
    name: "ຄ່າໃຊ້ຈ່າຍໃນການເຊົ່າ ແລະ ການຮ່ວມກຳມະສິດ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "617",
    parentCode: "61",
    name: "ຄ່າວິໄຈ ແລະ ຄົ້ນຄວ້າ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "618",
    parentCode: "61",
    name: "ຄ່າປະກອບເອກະສານ ແລະ ອື່ນໆທີ່ຕິດພັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "619",
    parentCode: "61",
    name: "ສ່ວນຫຼຸດຕ່າງໆ ທີ່ໄດ້ຮັບຈາກທາງນອກ",
    type: "expense",
    normalSide: "Cr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },

  {
    code: "62",
    parentCode: "6",
    name: "ຄ່າບໍລິການອື່ນໆ ຈາກທາງນອກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "621",
    parentCode: "62",
    name: "ຄ່າຂົນສົ່ງ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "622",
    parentCode: "62",
    name: "ຄ່າໂຄສະນາ, ລົງຂ່າວ, ໜັງສືພີມ-ຈັດພິມ, ປະຊາສຳພັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຈຳຫນ່າຍ",
  },
  {
    code: "623",
    parentCode: "62",
    name: "ຄ່າໄປສະນີ ແລະ ໂທລະຄົມມະນາຄົມ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "624",
    parentCode: "62",
    name: "ຄ່ານາຍໜ້າ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນຈຳຫນ່າຍ",
  },
  {
    code: "625",
    parentCode: "62",
    name: "ຄ່າເດີນທາງ, ກອງປະຊຸມ, ຮັບແຂກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "626",
    parentCode: "62",
    name: "ວຽກງານທາງການ, ທັດສະນະສຶກສາ, ຝຶກອົບຮົມ ແລະ ອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "627",
    parentCode: "62",
    name: "ຄ່າທຳນຽມທະນາຄານ ແລະ ຄ່າໃຊ້ຈ່າຍປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "628",
    parentCode: "62",
    name: "ຄ່າບໍລິການອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "629",
    parentCode: "62",
    name: "ສ່ວນຫຼຸດຕ່າງໆ ທີ່ໄດ້ຮັບໃນການບໍລິການອື່ນໆ ຈາກທາງນອກ",
    type: "expense",
    normalSide: "Cr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },

  {
    code: "63",
    parentCode: "6",
    name: "ລາຍຈ່າຍໃຫ້ພະນັກງານ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "631",
    parentCode: "63",
    name: "ຄ່າທົດແທນແຮງງານ ໃຫ້ພະນັກງານ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "632",
    parentCode: "63",
    name: "ເງິນບຳເນັດ ແລະ ຍ້ອງຍໍ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "633",
    parentCode: "63",
    name: "ເງິນນະໂຍບາຍການພັກຜ່ອນ ແລະ ສະຫວັດດີການ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "634",
    parentCode: "63",
    name: "ຜົນປະໂຫຍດດ້ານວັດຖຸ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "635",
    parentCode: "63",
    name: "ເງິນບຳລຸງໃຫ້ອົງການປະກັນສັງຄົມ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "636",
    parentCode: "63",
    name: "ເງິນນະໂຍບາຍຕ່າງໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "637",
    parentCode: "63",
    name: "ລາຍຈ່າຍດ້ານສັງຄົມອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "638",
    parentCode: "63",
    name: "ລາຍຈ່າຍອື່ນໆໃຫ້ພະນັກງານ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },

  {
    code: "64",
    parentCode: "6",
    name: "ອາກອນ, ຄ່າທຳນຽມ ແລະ ອື່ນໆ ປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "641",
    parentCode: "64",
    name: "ພາສີຂາເຂົ້າ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "642",
    parentCode: "64",
    name: "ພາສີຂາອອກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "643",
    parentCode: "64",
    name: "ອມພ ຫັກອອກບໍ່ໄດ້",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "644",
    parentCode: "64",
    name: "ພາສີທີ່ດິນ ແລະ ປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "647",
    parentCode: "64",
    name: "ຄ່າທຳນຽມ ແລະ ອາກອນສະແຕມ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "648",
    parentCode: "64",
    name: "ອາກອນ ແລະ ຄ່າທຳນຽມອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },

  {
    code: "65",
    parentCode: "6",
    name: "ລາຍຈ່າຍອື່ນໆ ໃນການທຸລະກິດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "651",
    parentCode: "65",
    name: "ຄ່າທຳນຽມສຳປະທານ ແລະ ລາຍຈ່າຍປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "652",
    parentCode: "65",
    name: "ມູນຄ່າສ່ວນຫຼຸດ ຈາກການຂາຍ ຊັບສົມບັດຄົງທີ່",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "653",
    parentCode: "65",
    name: "ເບ້ຍປະຊຸມ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "654",
    parentCode: "65",
    name: "ຂາດທຶນບ້ວງໜີ້ຮຽກເກັບບໍ່ໄດ້",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "655",
    parentCode: "65",
    name: "ພູດສ່ວນຜົນໄດ້ຮັບ ຈາກກິດຈະການຮ່ວມກັນ - ຂາດທຶນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "656",
    parentCode: "65",
    name: "ຄ່າປັບໃໝ, ເງິນຊ່ວຍໜູນທີ່ໄດ້ໃຫ້, ຂອງຂວັນ, ລາງວັນ ແລະ ເງິນຊ່ວຍບໍລິຈາກ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "657",
    parentCode: "65",
    name: "ຂາດທຶນຈາກການແລກປ່ຽນ ຊັບສົມບັດຄົງທີ່",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "658",
    parentCode: "65",
    name: "ລາຍຈ່າຍອື່ນໆ ໃນການທຸລະກິດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "66",
    parentCode: "6",
    name: "ລາຍຈ່າຍການເງິນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "661",
    parentCode: "66",
    name: "ລາຍຈ່າຍດອກເບ້ຍ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "662",
    parentCode: "66",
    name: "ສ່ວນຫຼຸດການຊຳລະສະສາງ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "663",
    parentCode: "66",
    name: "ຂາດທຶນຈາກອັດຕາແລກປ່ຽນເງິນຕາ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "664",
    parentCode: "66",
    name: "ສ່ວນປ່ຽນແປງ ມູນຄ່າຍຸຕິທຳ ຂອງເງິນລົງທຶນ ໃນວິສາຫະກິດຂາຮຸ້ນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "665",
    parentCode: "66",
    name: "ມູນຄ່າສ່ວນຫຼຸດ ບ້ວງຫຼັກຊັບລົງທຶນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "666",
    parentCode: "66",
    name: "ມູນຄ່າສ່ວນຫຼຸດ ເຄື່ອງມືການເງິນ ແລະ ເຄື່ອງມືປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "667",
    parentCode: "66",
    name: "ລາຍຈ່າຍສຸດທິ ຈາກການຂາຍຫຼັກຊັບໝູນທຶນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "668",
    parentCode: "66",
    name: "ລາຍຈ່າຍການເງິນອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "67",
    parentCode: "6",
    name: "ລາຍຈ່າຍສັງລວມ ຫຼັງອາກອນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "671",
    parentCode: "67",
    name: "ຄ່າເວນຄືນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "672",
    parentCode: "67",
    name: "ລາຍຈ່າຍຈາກໄພພິບັດທຳມະຊາດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "673",
    parentCode: "67",
    name: "ຂາດທຶນຈາກການຕີມູນຄ່າ (ຊັບສິນ-ໜີ້ສິນ) ທີ່ເປັນເງິນຕາຕ່າງປະເທດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "674",
    parentCode: "67",
    name: "ຜິດດ່ຽງຈາກການຕີມູນຄ່າ ຊັບສົມບັດຄົງທີ່ ຄືນໃໝ່ຫຼຸດລົງ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "675",
    parentCode: "67",
    name: "ຂາດທຶນຈາກການຊຳລະສະສາງ ຫຼື ການຄວບ ບໍລິສັດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "678",
    parentCode: "67",
    name: "ລາຍຈ່າຍສັງລວມອື່ນໆ ຫຼັງອາກອນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "6781",
    parentCode: "678",
    name: "ສ່ວນຫຼຸດ ຈາກລາຍການດັດແກ້ການຮັບຮອງນຳໃຊ້ຄັ້ງທຳອິດ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "6782",
    parentCode: "678",
    name: "ສ່ວນຫຼຸດ ຈາກການປ່ຽນແປງນະໂຍບາຍດ້ານບັນຊີ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "6783",
    parentCode: "678",
    name: "ສ່ວນຫຼຸດ ຈາກການແກ້ໄຂຂໍ້ຜິດພາດດ້ານບັນຊີ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "6788",
    parentCode: "678",
    name: "ລາຍຈ່າຍສັງລວມອື່ນໆ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "68",
    parentCode: "6",
    name: "ຫັກຄ່າຫຼຸ້ຍຫ້ຽນ, ຄ່າສູນເສຍມູນຄ່າ, ເງິນແຮ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "681",
    parentCode: "68",
    name: "ຫັກຄ່າໃຊ້ຈ່າຍ ບ້ວງຊັບສົມບັດຄົງທີ່ ການເງິນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "682",
    parentCode: "68",
    name: "ຫັກຄ່າຫຼຸ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "683",
    parentCode: "68",
    name: "ຫັກຄ່າຫຼຸ້ຍຫ້ຽນ ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "684",
    parentCode: "68",
    name: "ຫັກເງິນແຮ ເພື່ອລາຍຈ່າຍ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "685",
    parentCode: "68",
    name: "ຫັກຄ່າສູນເສຍມູນຄ່າ - ຊັບສົມບັດຄົງທີ່",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "686",
    parentCode: "68",
    name: "ຫັກຄ່າສູນເສຍມູນຄ່າ - ເຄື່ອງໃນສາງ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "687",
    parentCode: "68",
    name: "ຫັກຄ່າສູນເສຍມູນຄ່າ - ໜີ້ຕ້ອງຮັບທວງຍາກ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },
  {
    code: "688",
    parentCode: "68",
    name: "ຫັກຄ່າສູນເສຍມູນຄ່າ - ຊັບສິນການເງິນ",
    type: "expense",
    normalSide: "Dr",
    category: "ຕົ້ນທຸນບໍລິຫານ",
  },

  {
    code: "69",
    parentCode: "6",
    name: "ອາກອນກຳໄລ ແລະ ອາກອນປະເພດດຽວກັນ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "691",
    parentCode: "69",
    name: "ອາກອນກຳໄລ ທີ່ອີງໃສ່ກິດຈະການປົກກະຕິ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "694",
    parentCode: "69",
    name: "ລາຍຈ່າຍ - ອາກອນເຍື້ອນຊຳລະ",
    type: "expense",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "699",
    parentCode: "69",
    name: "ລາຍຮັບ - ອາກອນເຍື້ອນຊຳລະ",
    type: "expense",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  // ═══════════════════════════════════════════════
  // ປະເພດ 7 - ລາຍຮັບ (Income)
  // ═══════════════════════════════════════════════
  {
    code: "7",
    parentCode: null,
    name: "ປະເພດ 7 - ບັນດາ ບັນຊີ ລາຍຮັບ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "70",
    parentCode: "7",
    name: "ຂາຍຜະລິດຕະພັນທີ່ໄດ້ຜະລິດ, ສິນຄ້າ, ການໃຫ້ການບໍລິການ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "701",
    parentCode: "70",
    name: "ຂາຍຜະລິດຕະພັນສຳເລັດຮູບ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "702",
    parentCode: "70",
    name: "ຂາຍຜະລິດຕະພັນລະຫວ່າງກາງ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "704",
    parentCode: "70",
    name: "ຂາຍການບໍລິການກໍ່ສ້າງ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "705",
    parentCode: "70",
    name: "ຂາຍຜົນການຄົ້ນຄວ້າ, ການວິໄຈ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "707",
    parentCode: "70",
    name: "ຂາຍສິນຄ້າ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "708",
    parentCode: "70",
    name: "ຂາຍການບໍລິການອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "709",
    parentCode: "70",
    name: "ການຂາຍສົ່ງຄືນ ແລະ ສ່ວນຫຼຸດຕ່າງໆທີ່ຫຼຸດໃຫ້ລູກຄ້າ",
    type: "income",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "7091",
    parentCode: "709",
    name: "ການຂາຍສົ່ງຄືນ",
    type: "income",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },
  {
    code: "7092",
    parentCode: "709",
    name: "ສ່ວນຫຼຸດຕ່າງໆທີ່ຫຼຸດໃຫ້ລູກຄ້າ",
    type: "income",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "71",
    parentCode: "7",
    name: "ລາຍຮັບຈາກ ກິດຈະການສຳຮອງ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "711",
    parentCode: "71",
    name: "ຂາຍເສດເຫຼືອຜະລິດຕະພັນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "712",
    parentCode: "71",
    name: "ລາຍຮັບຄ່າເຊົ່າຕ່າງໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "714",
    parentCode: "71",
    name: "ກຳໄລຈາກເງິນມັດຈຳເຄື່ອງຫຸ້ມຫໍ່",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "715",
    parentCode: "71",
    name: "ລາຍຮັບຄ່ານາຍໜ້າ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "717",
    parentCode: "71",
    name: "ລາຍຮັບຄ່າຂົນສົ່ງ ແລະ ຄ່າໃຊ້ຈ່າຍຕ່າງໆທີ່ເກັບນຳລູກຄ້າ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "718",
    parentCode: "71",
    name: "ລາຍຮັບຈາກ ກິດຈະການສຳຮອງອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "719",
    parentCode: "71",
    name: "ສ່ວນຫຼຸດລາຄາທີ່ໄດ້ຫຼຸດໃຫ້",
    type: "income",
    normalSide: "Dr",
    category: "ອື່ນໆ",
  },

  {
    code: "74",
    parentCode: "7",
    name: "ລາຍຮັບ ເງິນຊ່ວຍໜູນ ໃນການທຸລະກິດ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "741",
    parentCode: "74",
    name: "ເງິນຊ່ວຍໜູນ ດຸ່ນດ່ຽງ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "748",
    parentCode: "74",
    name: "ເງິນຊ່ວຍໜູນ ໃນການທຸລະກິດ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "75",
    parentCode: "7",
    name: "ລາຍຮັບອື່ນໆ ໃນການດຳເນີນງານປົກກະຕິ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "751",
    parentCode: "75",
    name: "ຄ່າທຳນຽມ ສຳປະທານ ແລະ ຄ່າທຳນຽມປະເພດດຽວກັນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "752",
    parentCode: "75",
    name: "ມູນຄ່າສ່ວນໄດ້ ຈາກການຂາຍ ຊັບສົມບັດຄົງທີ່ ທີ່ບໍ່ແມ່ນການເງິນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "752.001",
    parentCode: "752",
    name: "ມູນຄ່າສ່ວນໄດ້ ຈາກການຂາຍ ຊັບສົມບັດຄົງທີ່ - ອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "753",
    parentCode: "75",
    name: "ເບ້ຍປະຊຸມ ແລະ ຄ່າທົດແທນຜູ້ບໍລິຫານ, ຜູ້ຈັດການ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "754",
    parentCode: "75",
    name: "ພູດສ່ວນເງິນຊ່ວຍໜູນກໍ່ສ້າງພື້ນຖານ ທີ່ໂອນເຂົ້າຜົນໄດ້ຮັບໃນປີ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "755",
    parentCode: "75",
    name: "ພູດສ່ວນຜົນໄດ້ຮັບ ຈາກກິດຈະການຮ່ວມ - ກຳໄລ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "756",
    parentCode: "75",
    name: "ເງິນບໍລິຈາກທີ່ໄດ້ຮັບ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "757",
    parentCode: "75",
    name: "ສ່ວນໄດ້ຈາກການສະສາງຊັບສິນ ພູດສ່ວນເງິນຊ່ວຍໜູນກໍ່ສ້າງພື້ນຖານ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "758",
    parentCode: "75",
    name: "ລາຍຮັບອື່ນໆ ຈາກການດຳເນີນງານປົກກະຕິ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "76",
    parentCode: "7",
    name: "ລາຍຮັບການເງິນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "761",
    parentCode: "76",
    name: "ລາຍຮັບ ເງິນປັນຜົນ ແລະ ລາຍຮັບດອກເບ້ຍ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7611",
    parentCode: "761",
    name: "ລາຍຮັບ ເງິນປັນຜົນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7612",
    parentCode: "761",
    name: "ລາຍຮັບ ດອກເບ້ຍ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "762",
    parentCode: "76",
    name: "ສ່ວນຫຼຸດ ຮັບຈາກການຊຳລະເງິນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "763",
    parentCode: "76",
    name: "ກຳໄລຈາກອັດຕາແລກປ່ຽນເງິນຕາ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "764",
    parentCode: "76",
    name: "ລາຍຮັບ ຈາກຊັບສົມບັດຄົງທີ່ການເງິນອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "765",
    parentCode: "76",
    name: "ມູນຄ່າສ່ວນເກີນ ບ້ວງຫຼັກຊັບລົງທຶນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "766",
    parentCode: "76",
    name: "ມູນຄ່າສ່ວນເກີນ ເຄື່ອງມືການເງິນ ແລະ ເຄື່ອງມືປະເພດດຽວກັນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "767",
    parentCode: "76",
    name: "ລາຍຮັບສຸດທິ ຈາກການຂາຍຫຼັກຊັບໜູນທຶນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "768",
    parentCode: "76",
    name: "ລາຍຮັບການເງິນອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "77",
    parentCode: "7",
    name: "ລາຍຮັບສັງລວມ ຫຼັງອາກອນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "773",
    parentCode: "77",
    name: "ສ່ວນໄດ້ຈາກການຕີມູນຄ່າ (ຊັບສິນ-ໜີ້ສິນ) ທີ່ເປັນເງິນຕາຕ່າງປະເທດ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "774",
    parentCode: "77",
    name: "ສ່ວນໄດ້ຈາກການຕີມູນຄ່າ ຊັບສົມບັດຄົງທີ່ຄືນໃໝ່ເພີ່ມຂຶ້ນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "775",
    parentCode: "77",
    name: "ສ່ວນໄດ້ຈາກການຊຳລະສະສາງ ຫຼື ການຄວບ ບໍລິສັດ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "778",
    parentCode: "77",
    name: "ລາຍຮັບສັງລວມອື່ນໆ ຫຼັງອາກອນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7781",
    parentCode: "778",
    name: "ສ່ວນໄດ້ຈາກລາຍການດັດແກ້ການຮັບຮອງນຳໃຊ້ຄັ້ງທຳອິດ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7782",
    parentCode: "778",
    name: "ສ່ວນໄດ້ຈາກການປ່ຽນແປງນະໂຍບາຍດ້ານບັນຊີ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7783",
    parentCode: "778",
    name: "ສ່ວນໄດ້ຈາກການແກ້ໄຂຂໍ້ຜິດພາດດ້ານບັນຊີ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "7788",
    parentCode: "778",
    name: "ລາຍຮັບສັງລວມອື່ນໆ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },

  {
    code: "78",
    parentCode: "7",
    name: "ເກັບຄືນ ຄ່າຫຼຸ້ຍຫ້ຽນ, ຄ່າສູນເສັຍມູນຄ່າ ແລະ ເງິນແຮ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "782",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າຫຼຸ້ຍຫ້ຽນ - ຊັບສົມບັດຄົງທີ່ ມີຕົວຕົນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "783",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າຫຼຸ້ຍຫ້ຽນ - ຊັບສົມບັດຄົງທີ່ ບໍ່ມີຕົວຕົນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "784",
    parentCode: "78",
    name: "ເກັບຄືນ ເງິນແຮ ເພື່ອລາຍຈ່າຍ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "785",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າສູນເສຍມູນຄ່າ - ຊັບສົມບັດຄົງທີ່",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "786",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າສູນເສຍມູນຄ່າ - ເຄື່ອງໃນສາງ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "787",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າສູນເສຍມູນຄ່າ - ໜີ້ຕ້ອງຮັບທວງຍາກ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
  {
    code: "788",
    parentCode: "78",
    name: "ເກັບຄືນ ຄ່າສູນເສຍມູນຄ່າ - ຊັບສິນການເງິນ",
    type: "income",
    normalSide: "Cr",
    category: "ອື່ນໆ",
  },
];
// เพิ่มบรรทัดนี้ต่อท้าย file เดียวกัน
export const DEFAULT_ACCOUNT_CODES = new Set(
  DEFAULT_CHART_OF_ACCOUNTS.map((a) => a.code)
);
/**
 * Seed chart of accounts for a new company on register
 */
export async function seedChartOfAccounts(Account, companyId, userId) {
  const docs = DEFAULT_CHART_OF_ACCOUNTS.map((acc) => ({
    ...acc,
    companyId,
    userId,
    balanceDr: 0,
    balanceCr: 0,
  }));
  await Account.insertMany(docs, { ordered: false });
}

export const ACCOUNT_DEPTH_LIMIT = {
  606: 1, // 606 → 606x.xxx ได้, แต่ 606x.xxx → ??? ไม่ได้
};
/**
 * หา "ต้นสาย" ของ account code ว่าอยู่ภายใต้ ACCOUNT_DEPTH_LIMIT ตัวไหน
 * และคืนค่า maxDepth ที่อนุญาต
 */
export const getDepthLimit = (code) => {
  for (const [rootCode, maxDepth] of Object.entries(ACCOUNT_DEPTH_LIMIT)) {
    if (String(code).startsWith(String(rootCode))) {
      return { rootCode, maxDepth };
    }
  }
  return null;
};

/**
 * นับว่า account นี้อยู่ลึกแค่ไหนจาก rootCode
 * โดยไล่ขึ้นไปหา parent จนถึง root
 * คืนค่า depth (1 = ลูกโดยตรงของ root)
 */
export const getCurrentDepth = async (parentCode, companyId, AccountModel) => {
  let depth = 0;
  let currentCode = parentCode;

  while (currentCode) {
    // ตรวจว่า currentCode เป็น root ใน config ไหม
    if (ACCOUNT_DEPTH_LIMIT[currentCode] !== undefined) {
      return depth; // depth ที่ parentCode อยู่ห่างจาก root
    }

    // ไล่ขึ้นไปหา parent
    const account = await AccountModel.findOne({
      code: currentCode,
      companyId,
    })
      .select("parentCode")
      .lean();

    if (!account?.parentCode) break;

    currentCode = account.parentCode;
    depth++;

    if (depth > 10) break; // ป้องกัน infinite loop
  }

  return depth;
};
